// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $('#go').click(function() {
      var worker;
      worker = new Worker('show-order.js');
      return worker.addEventListener('message', function(event) {
        return console.log(event.data);
      });
    });
  });

}).call(this);
